language: c

os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libssl-dev; fi

script: ./configure --enable-ssl && make

compiler:
  - clang
  - gcc

