language: c

before_install:
	-  if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y install libssl-dev; fi

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
	- ./configure --enable-ssl; make
	
